// [최우선 전역 설정] Node.js 환경에서 Supabase SDK의 WebSocket 참조 에러를 원천 차단하는 더미 폴리필
// 모든 import보다 먼저 실행되어야 하므로 반드시 파일 최상단에 위치
if (typeof (globalThis as any).WebSocket === 'undefined') {
  (globalThis as any).WebSocket = class DummyWebSocket {
    constructor() {}
    addEventListener() {}
    removeEventListener() {}
    close() {}
    send() {}
  };
}

import { app, BrowserWindow, Tray, Menu, nativeImage, ipcMain, shell, Notification } from 'electron'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import fs from 'node:fs'
import { startLocalServer, setServerCollecting } from './local-server'
import { startDataCleanupScheduler } from './data-manager'
import { startIdleMonitor, stopIdleMonitor, onSystemIdle } from './idle-monitor'
import { startClipboardMonitor, stopClipboardMonitor } from './clipboard-monitor'
import { runGateKeeper } from './analyzer/gate-keeper'
import { autoUpdater } from 'electron-updater'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// The built directory structure
//
// ├─┬─┬ dist
// │ │ └── index.html
// │ │
// │ ├─┬ dist-electron
// │ │ ├── main.js
// │ │ └── preload.mjs
// │
process.env.APP_ROOT = path.join(__dirname, '..')

// 🚧 Use ['ENV_NAME'] avoid vite:define plugin - Vite@2.x
export const VITE_DEV_SERVER_URL = process.env['VITE_DEV_SERVER_URL']
export const MAIN_DIST = path.join(process.env.APP_ROOT, 'dist-electron')
export const RENDERER_DIST = path.join(process.env.APP_ROOT, 'dist')

process.env.VITE_PUBLIC = VITE_DEV_SERVER_URL ? path.join(process.env.APP_ROOT, 'public') : RENDERER_DIST

let win: BrowserWindow | null
let tray: Tray | null = null
let isQuitting = false
let isCollecting = true
let latestIdea: Record<string, unknown> | null = null

function createWindow() {
  win = new BrowserWindow({
    width: 900,
    height: 700,
    frame: false, // OS 순정 상단바 제거
    resizable: false, // 더블클릭 최대화 방지
    maximizable: false, // 최대화 비활성화
    icon: path.join(process.env.VITE_PUBLIC, 'icon.png'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.mjs'),
    },
  })

  // IPC 이벤트 리스너 등록 (최소화 및 트레이로 숨김)
  ipcMain.on('window-minimize', () => {
    win?.minimize()
  })

  ipcMain.on('window-close', () => {
    win?.hide()
  })

  // 외부 브라우저 URL 팝업 배관 개통
  ipcMain.on('open-external-url', (_event, url) => {
    shell.openExternal(url)
  })

  // config.json 읽기/쓰기 IPC 핸들러
  ipcMain.handle('config-read', () => {
    try {
      const configPath = path.join(app.getPath('userData'), 'config.json')
      if (!fs.existsSync(configPath)) return null
      return JSON.parse(fs.readFileSync(configPath, 'utf-8'))
    } catch { return null }
  })

  ipcMain.handle('config-write', (_event, config: Record<string, unknown>) => {
    try {
      const configPath = path.join(app.getPath('userData'), 'config.json')
      fs.writeFileSync(configPath, JSON.stringify(config, null, 2), 'utf-8')
      return { ok: true }
    } catch (err) {
      return { ok: false, error: (err as Error).message }
    }
  })

  // 최근 분석 결과 IPC 핸들러
  ipcMain.handle('get-latest-idea', () => {
    return latestIdea
  })

  // 라이브 테스트용 알림창 강제 발사 배관 개통
  ipcMain.on('test-notification', () => {
    if (Notification.isSupported()) {
      const iconPath = path.join(process.env.VITE_PUBLIC, 'icon.png')
      const n = new Notification({
        title: '💡 New Idea Captured (GOLD)',
        body: 'A high-quality business idea has been generated by Limina!',
        icon: nativeImage.createFromPath(iconPath)
      })
      n.show()
      console.log('[Limina TestNotification] Alert popped up successfully.')
    } else {
      console.warn('[Limina TestNotification] System notification is not supported.')
    }
  })

  // Test active push message to Renderer-process.
  win.webContents.on('did-finish-load', () => {
    win?.webContents.send('main-process-message', (new Date).toLocaleString())
  })

  // 창 닫기 이벤트 가로채기 (Hide to Tray)
  win.on('close', (event) => {
    if (!isQuitting) {
      event.preventDefault()
      win?.hide()
    }
  })

  // 최소화 이벤트 가로채기 (Hide to Tray)
  win.on('minimize', (event: any) => {
    event.preventDefault()
    win?.hide()
  })

  if (VITE_DEV_SERVER_URL) {
    win.loadURL(VITE_DEV_SERVER_URL)
  } else {
    win.loadFile(path.join(RENDERER_DIST, 'index.html'))
  }
}

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
    win = null
  }
})

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

function createTray() {
  const iconPath = path.join(process.env.VITE_PUBLIC, 'icon.png')
  const icon = nativeImage.createFromPath(iconPath)
  // 윈도우 시스템 트레이 표준 크기(16x16)로 조절
  const resizedIcon = icon.resize({ width: 16, height: 16 })
  
  tray = new Tray(resizedIcon)
  
  // 트레이 아이콘 더블클릭 시 메인 창 토글 (보이기/숨기기)
  tray.on('double-click', () => {
    if (win) {
      if (win.isVisible()) {
        win.hide()
      } else {
        win.show()
        win.focus()
      }
    }
  })

  updateTrayMenu()
}

function updateTrayMenu() {
  if (!tray) return

  // 수집 상태에 따라 마우스 호버 툴팁 텍스트 동적 업데이트
  const tooltipText = isCollecting ? 'Limina - 동작 중' : 'Limina - 수집 중지됨'
  tray.setToolTip(tooltipText)

  // 트레이 우클릭 컨텍스트 메뉴 조립
  const contextMenu = Menu.buildFromTemplate([
    {
      label: '앱 열기 (Open)',
      click: () => {
        win?.show()
        win?.focus()
      }
    },
    {
      label: isCollecting ? '수집 중지 (Stop)' : '수집 시작 (Start)',
      click: () => {
        isCollecting = !isCollecting
        
        // local-server 및 idle-monitor 수집 중단/재개 연동
        setServerCollecting(isCollecting)
        if (isCollecting) {
          startIdleMonitor()
          startClipboardMonitor(win)
          console.log('[Limina] Background collection resumed via Tray.')
        } else {
          stopIdleMonitor()
          stopClipboardMonitor()
          console.log('[Limina] Background collection paused via Tray.')
        }
        
        // 툴팁 및 메뉴 상태 실시간 재갱신
        updateTrayMenu()
      }
    },
    { type: 'separator' },
    {
      label: '종료 (Exit)',
      click: () => {
        isQuitting = true
        app.quit()
      }
    }
  ])

  tray.setContextMenu(contextMenu)
}

app.whenReady().then(() => {
  // Windows 알림창 팝업 차단 우회용 고유 AppUserModelId 강제 등록
  if (process.platform === 'win32') {
    app.setAppUserModelId('com.Limina.agent')
  }

  startLocalServer()
  startDataCleanupScheduler()
  // idle-monitor가 울리면 gate-keeper 분석 파이프라인 실행
  onSystemIdle((logFilePath, signal) => {
    runGateKeeper(logFilePath, signal).then(result => {
      if (result && result.grade !== 'BURN' && result.grade !== 'EMPTY') {
        latestIdea = result as unknown as Record<string, unknown>
        win?.webContents.send('new-idea', result)
      }
    }).catch(err => {
      console.error('[Limina] GateKeeper uncaught error:', (err as Error).message)
    })
  })
  startIdleMonitor()
  createWindow()
  startClipboardMonitor(win)
  createTray()

  // 자동 업데이트 (GitHub Releases 기반)
  // 자동 업데이트 (GitHub Releases 기반)
  autoUpdater.autoDownload = true
  autoUpdater.autoInstallOnAppQuit = true

  autoUpdater.on('update-available', (info) => {
    console.log('[Limina AutoUpdater] Update available:', info.version)
    win?.webContents.send('update-status', { status: 'available', version: info.version })
  })

  autoUpdater.on('update-downloaded', (info) => {
    console.log('[Limina AutoUpdater] Update downloaded:', info.version)
    win?.webContents.send('update-status', { status: 'downloaded', version: info.version })
  })

  autoUpdater.on('error', (err) => {
    console.error('[Limina AutoUpdater] Error:', err.message)
    win?.webContents.send('update-status', { status: 'error', error: err.message })
  })

  ipcMain.on('restart-app', () => {
    autoUpdater.quitAndInstall()
  })

  autoUpdater.checkForUpdatesAndNotify().catch(() => {})
})

app.on('before-quit', () => {
  isQuitting = true
  stopIdleMonitor()
  stopClipboardMonitor()
})
